# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle      

name: Auto Build CI

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Workflow'
        required: true
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout ViaVersion
      uses: tibdex/github-action-clone-repo@v1
      with:
        repository: ViaVersion/ViaVersion
        branch: master
        token: ${{ secrets.GITHUB_TOKEN }}
      path: viaversion

    - name: Get last commit hash of ViaVersion
      id: last_commit
      run: |
        cd viaversion
        echo "last_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "last_commit_date=$(git log -1 --format=%cd --date=short | tr -d '-')"

    - name: Check if commit has changed since last run
      id: changed
      uses: tmatignon/commit-comparison-action@v1
      with:
        repo: ViaVersion/ViaVersion
        branch: master
        previous-sha: ${{ steps.last_commit.outputs.last_commit_sha }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew shadowJar

    - name: Get current date
      id: date
      run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: DirtMultiversion-SNAPSHOT-${{ steps.date.outputs.date }}
        path: ./build/libs/*.jar
        retention-days: 30

    - name: Skip if no changes
      if: ${{ steps.changed.outputs.changed == 'false' }}
      continue-on-error: true
      run: |
        echo "No changes detected. Skipping workflow."
        exit 1

    - name: Create GitHub Release
      if: ${{ steps.changed.outputs.changed == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: "Build ${{ steps.date.outputs.date }}"
        draft: false
        prerelease: false
        files: ./build/libs/*.jar