name: Auto Build CI

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Workflow'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout current repo (for scripts)
      uses: actions/checkout@v4

    - name: Download last commit (if exists)
      uses: actions/download-artifact@v4
      with:
        name: last-commit
        path: ./
      continue-on-error: true

    - name: Clone ViaVersion repository
      uses: actions/checkout@v4
      with:
        repository: ViaVersion/ViaVersion
        ref: master
        path: viaversion

    - name: Move repository to viaversion folder
      run: |
        mv ViaVersion viaversion

    - name: Get current commit hash
      id: current_commit
      run: |
        cd viaversion
        echo "current_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare with last commit
      id: compare
      run: |
        if [ -f .last_commit_sha ]; then
          last_sha=$(cat .last_commit_sha)
          if [ "$last_sha" == "${{ steps.current_commit.outputs.current_sha }}" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew shadowJar

    - name: Get current date
      id: date
      run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DirtMultiversion-SNAPSHOT-${{ steps.date.outputs.date }}
        path: ./build/libs/*.jar
        retention-days: 30

    - name: Generate .last_commit_sha file
      if: ${{ steps.compare.outputs.changed == 'true' }}
      run: |
        echo "${{ steps.current_commit.outputs.current_sha }}" > .last_commit_sha

    - name: Upload .last_commit_sha for next run
      if: ${{ steps.compare.outputs.changed == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: last-commit
        path: .last_commit_sha

    - name: Skip if no changes
      if: ${{ steps.compare.outputs.changed == 'false' }}
      run: |
        echo "No changes detected. Skipping workflow."
        exit 0

    - name: Create GitHub Release
      if: ${{ steps.compare.outputs.changed == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: "Build ${{ steps.date.outputs.date }}"
        draft: false
        prerelease: false
        files: ./build/libs/*.jar